### PR TITLE
Update the compatibility table of the dump and Aura versions

### PR DESCRIPTION
**Pull request by NataliaIvakina**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1892.surge.sh

Updated pages:
- [Push to cloud](https://neo4j-docs-operations-1892.surge.sh/operations-manual/4.3/tools/neo4j-admin/push-to-cloud)

**Review by fiquick — APPROVED** [review]
Looks good!

**Review by renetapopova — COMMENTED** [review]
It looks good, but I think it would be helpful to add an admonition that if they want to upload their 4.3 database in Aura, they need to upgrade it first to 4.4 and then use the `neo4j-admin push-to-cloud` command.

**Comment by NataliaIvakina** [comment]
> It looks good, but I think it would be helpful to add an admonition that if they want to upload their 4.3 database in Aura, they need to upgrade it first to 4.4 and then use the `neo4j-admin push-to-cloud` command.

@fiquick, what do you think?

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1892.surge.sh

Updated pages:
- [Push to cloud](https://neo4j-docs-operations-1892.surge.sh/operations-manual/4.3/tools/neo4j-admin/push-to-cloud)

**Pull request merged**
