### PR TITLE
Group configuration settings

### PR DESCRIPTION
**Pull request by NataliaIvakina**

### CODE REVIEW

**Comment by NataliaIvakina** [comment]
[Restructure config.settings](https://trello.com/c/umN9P4jm/101-restructure-configsettings)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1049.surge.sh

**Review by renetapopova — COMMENTED** [review]
Thanks, @NataliaIvakina! It looks good to me. I just wonder if we should move all the Server settings under DBMS, as servers are introduced in 5.x.

**Comment by renetapopova** [comment]
Maybe, @mauvo could be the right person to ask.

**Pull request merged**
