### PR TITLE
Updating a last command that was still install-service

### PR DESCRIPTION
**Pull request by lidiazuin**
Instead of the correct `windows-service`

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-673.surge.sh

**Comment by renetapopova** [comment]
I think this should be verified by someone with Windows.

**Comment by lidiazuin** [comment]
@renetapopova this was already updated before https://github.com/neo-technology/neo4j-manual-modeling/pull/3350, it's just that there was one last code block that remained outdated (my mistake)

**Review by renetapopova — APPROVED** [review]
Approved ✅

**Pull request merged**
