### PR TITLE
replacing an existing database is only for EE

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1937.surge.sh

Updated pages:
- [Restore a database dump](https://neo4j-docs-operations-1937.surge.sh/operations-manual/5/backup-restore/restore-dump)

**Review by NataliaIvakina — APPROVED** [review]
I think this is a good fast fix. But I'm wondering if it's clear enough that in CE you have to shut down your database before running the command.
I guess, in CE, you have only one option to replace the database. In EE, you can replace the db or create a new one (probably in addition to existing).

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1937.surge.sh

Updated pages:
- [Restore a database dump](https://neo4j-docs-operations-1937.surge.sh/operations-manual/5/backup-restore/restore-dump)

**Comment by renetapopova** [comment]
> I think this is a good fast fix. But I'm wondering if it's clear enough that in CE you have to shut down your database before running the command. I guess, in CE, you have only one option to replace the database. In EE, you can replace the db or create a new one (probably in addition to existing).

Yes, in CE, you can only replace it as `CREATE DATABASE` is not available.

**Review by NataliaIvakina — APPROVED** [review]
Looks good! Thank you, Reneta!

**Pull request merged**
