### PR TITLE
Add an MVCC related metric

### PR DESCRIPTION
**Pull request by NataliaIvakina**
see https://github.com/neo-technology/neo4j/commit/758960863da689d7b47d6562037e4bd4ea4259cb#diff-824ff32f02805ec284d529daf30fe070bcd5f58a3c7be32bced227fa75c43c7b

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1924.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1924.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Review by renetapopova — COMMENTED** [review]
I think Misha should review this one, just to be aware that we're documenting an MVCC metric.

**Comment by NataliaIvakina** [comment]
> I think Misha should review this one, just to be aware that we're documenting an MVCC metric.

Yes, of course. I'll tag him as a reviewer later. But we have already one MVCC related metric in the docs -

**Comment by MishaDemianenko** [comment]
Hi folks, so I have a question. MVCC is not released even for beta users atm and there is no mentioning of that in any other parts of docs. Is it okay to have those metrics described in public documentation for a feature that does not exist yet give or take?

**Comment by NataliaIvakina** [comment]
> Hi folks, so I have a question. MVCC is not released even for beta users atm and there is no mentioning of that in any other parts of docs. Is it okay to have those metrics described in public documentation for a feature that does not exist yet give or take?

@renetapopova, @stefano-ottolenghi, considering we already have one MVCC-related metric in the documentation, what do you think?

@stefano-ottolenghi, is it possible to comment out those metrics in the docs (to hide them from users for some time)? Will it break our test?

**Comment by stefano-ottolenghi** [comment]
> Will it break our test?

It will, because they are publicly available metrics. We can add a fence to explicitly exclude them until we want to surface them, if there's a need for that (but then the question is: why are they not in the `internal` namespace?).

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1924.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1924.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Review by MishaDemianenko — APPROVED** [review]

**Pull request merged**
