### PR TITLE
Restructure of the introduction page

### PR DESCRIPTION
**Pull request by lidiazuin**

### CODE REVIEW

**Comment by renetapopova** [comment]
Overall, it looks like what we discussed with Natalia. However, we talked about adding a new section before "There are two editions of Neo4j to choose from, the <<community-edition, _Community Edition_>> and the <<", which will be called **Neo4j editions** and then paraphrase the sentence to remove the links. It could be something like:

There are two editions of self-managed Neo4j to choose from, the Community Edition and the Enterprise Edition.
The Enterprise Edition includes all that Community Edition has to offer, plus extra enterprise requirements such as backups, clustering, and failover capabilities.
The following table compares the available key features in both editions:
_and then follows the table_

**Comment by renetapopova** [comment]
The Versioning section should be kept as it is.

**Comment by lidiazuin** [comment]
> The Versioning section should be kept as it is.

Ok, I will revert this. In the Trello card, it was moved to the last topic. :)

**Review by renetapopova — COMMENTED** [review]
I've updated my comment to make it more precise.

**Review by renetapopova — APPROVED** [review]
Looks good, thanks!

**Comment by renetapopova** [comment]
If you decide to cherry-pick it to 4.4 as well, make sure you compare the key features as they will most probably differ from the ones in 5.x.

**Comment by lidiazuin** [comment]
> [`065bb99`](/neo4j/docs-operations/commit/065bb99cb1b0b49a678f6d388a64a0c1b7f295ed)

Right, if you want to take a look at the 4.4 cherry-pick, here's the link https://github.com/neo4j/docs-operations/pull/1274

**Comment by lidiazuin** [comment]
> If you decide to cherry-pick it to 4.4 as well, make sure you compare the key features as they will most probably differ from the ones in 5.x. Yeah, I just checked, and they are structured in a different way. So, please, keep them as they are, as the new way of organizing the features was introduced in 5.x.

Right, if you want to take a look at the 4.4 cherry-pick, here's the link https://github.com/neo4j/docs-operations/pull/1274

**Pull request merged**
