### PR TITLE
Restructure the table of file def locations

### PR DESCRIPTION
**Pull request by NataliaIvakina**
Split the original table into several pieces depending on the file type

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1330.surge.sh

Updated pages:
- [Default file locations](https://neo4j-docs-operations-1330.surge.sh/operations-manual/5/configuration/file-locations)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1330.surge.sh

Updated pages:
- [Default file locations](https://neo4j-docs-operations-1330.surge.sh/operations-manual/5/configuration/file-locations)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1330.surge.sh

Updated pages:
- [Default file locations](https://neo4j-docs-operations-1330.surge.sh/operations-manual/5/configuration/file-locations)

**Review by renetapopova — APPROVED** [review]
Love it. Thanks, @NataliaIvakina

**Pull request merged**
