### PR TITLE
Add missing genai.vector.listEncodingProviders

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1536.surge.sh

Updated pages:
- [Procedures](https://neo4j-docs-operations-1536.surge.sh/operations-manual/5/reference/procedures)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1536.surge.sh

Updated pages:
- [Procedures](https://neo4j-docs-operations-1536.surge.sh/operations-manual/5/reference/procedures)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1536.surge.sh

Updated pages:
- [Procedures](https://neo4j-docs-operations-1536.surge.sh/operations-manual/5/reference/procedures)

**Review by NataliaIvakina — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
