### PR TITLE
Remove test-skip anotations for cdc docs

### PR DESCRIPTION
**Pull request by l-heemann**
CDC feature flag was enabled by default recently

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1167.surge.sh

**Review by stefano-ottolenghi — APPROVED** [review]

**Comment by renetapopova** [comment]
Please, cherry-pick this PR into 5.x if it is related to the current version. Otherwise, label it with the applicable version. Thanks.

**Comment by l-heemann** [comment]
Hi, Is the cherry picking something I should do or does the docs team have a process for this? @renetapopova

**Comment by renetapopova** [comment]
Usually, the docs team does it.

**Pull request merged**
