### PR TITLE
Remove commented out labels in favor of roles.

### PR DESCRIPTION
**Pull request by stefano-ottolenghi**
Labels are not needed for testing anymore, as of https://github.com/neo4j/docs-testing/commit/f6ecaa895cc75153d9c6e5bab12f721c0c780430 .

The failing tests are unrelated to this PR.

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1769.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1769.surge.sh/operations-manual/5/configuration/configuration-settings)

**Review by NataliaIvakina — APPROVED** [review]
LGTM! Thank you, @stefano-ottolenghi!

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1769.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1769.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by stefano-ottolenghi** [comment]
Ported in 5.x via https://github.com/neo4j/docs-operations/commits/5.x/

**Pull request merged**
