### PR TITLE
Fix duplicated entry for `page_cache.page_cancelled_faults` metric

### PR DESCRIPTION
**Pull request by brunobuss**
There is a duplicated entry for that metric, with the only difference being one has the description spelled `canceled` and the other one `cancelled`.

I merged both into the first entry just because because that matches the order of the metrics in the code-base.

### CODE REVIEW

**Comment by brunobuss** [comment]
Spotted this while reading [the docs](https://neo4j.com/docs/operations-manual/current/monitoring/metrics/reference/#db-page-cache-metrics).

I think this is my first PR here, so let me know if I did everything correctly with labels and stuff :)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1312.surge.sh

**Review by NataliaIvakina — APPROVED** [review]
Thank you, @brunobuss! LGTM!

**Comment by renetapopova** [comment]
This PR needs to be cherry-picked to 5.x.

**Comment by NataliaIvakina** [comment]
Done!

**Pull request merged**
