### PR TITLE
add deprecated causal clustering metrics

### PR DESCRIPTION
**Pull request by AlexicaWright**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1423.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1423.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Comment by NataliaIvakina** [comment]
Looks good! I have one suggestion: to move labels `Deprecated in 5.0` to the table headings.

**Review by NataliaIvakina — APPROVED** [review]

**Comment by renetapopova** [comment]
> Looks good! Thank you, @AlexicaWright! I have one suggestion: to move the label `Deprecated in 5.0` to the table headings.

Looks good. I think Natalia's comment is reasonable. We don't have labels in the descriptions in the codebase. Better to keep the descriptions clean.

**Review by renetapopova — COMMENTED** [review]
I left my comment inline.

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1423.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1423.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Review by renetapopova — APPROVED** [review]
Thanks, @AlexicaWright!

**Review by nick-giles-neo — APPROVED** [review]

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1423.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1423.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Pull request merged**
