### PR TITLE
Update `server.metrics.filter`, add new 5.26 configuration settings 

### PR DESCRIPTION
**Pull request by NataliaIvakina**
Related to https://github.com/neo-technology/neo4j/pull/27660, https://github.com/neo-technology/neo4j/pull/27785, and https://github.com/neo-technology/neo4j/pull/27962.
These are implemented in 5.26

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1933.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1933.surge.sh/operations-manual/5/configuration/configuration-settings)

**Review by gjmwoods — APPROVED** [review]
this one might belong to another change `server.metrics.filter`. Thanks 🙇

**Comment by NataliaIvakina** [comment]
Test failure is not related to this PR

**Review by gfx54b — APPROVED** [review]
Good on https://github.com/neo-technology/neo4j/pull/27962

**Pull request merged**
