### PR TITLE
Fix the failing tests

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1040.surge.sh

**Comment by renetapopova** [comment]
Hey @stefano-ottolenghi, could you be able to help me with fixing this test? I've fixed several things but it stil complains. 🤷‍♀️

**Comment by stefano-ottolenghi** [comment]
You changed the defaults and the `v` in the description correctly. The real culprit is in fact an older change https://github.com/neo4j/docs-operations/pull/998 when the version labels for `--strict` were added. The testing code is upset by them as they don't match the actual command descriptions. Please leave this open while I look into this, update the code, and re-run the tests to verify that it will all be correct :)

**Comment by renetapopova** [comment]
Thanks, @stefano-ottolenghi! Could we be able to modify the test to skip the labels? I tried to move them around, but there aren't many possibilities, given that it's a table. Thanks a lot for helping me.

**Comment by stefano-ottolenghi** [comment]
Yeah exactly, that's the idea: skip labels :)

**Comment by stefano-ottolenghi** [comment]
@renetapopova I altered the testing code and also made the `date` labels into proper labels, such as `label:date[Changed in 5.8]`, so that all tests on neo4j-admin commands are green again! :)

**Pull request merged**
