### PR TITLE
Reword the warning about the use of the incremental import

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-865.surge.sh

**Review by davidoliverSP2 — APPROVED** [review]
Thanks @renetapopova - this looks like a sensible improvement, and the warning can be removed in the future when the feature is more mature.

One thing I noticed though is that the `Enterprise Edition` label is a bit prominent - perhaps it can be suppressed for all headers beneath **Incremental import**?
Screenshot 2023-06-22 at 15 00 40

**Comment by renetapopova** [comment]
Good catch, @davidoliverSP2! I haven't noticed it at all. We certainly don't need all these labels 😄!

**Comment by renetapopova** [comment]
Hmm, I don't know how to suppress it. @davidoliverSP2, could you be able to help me with that?

**Comment by davidoliverSP2** [comment]
> Hmm, I don't know how to suppress it. @davidoliverSP2, could you be able to help me with that?

Sure - I'll raise a card on the wall and look into it. You can merge this PR as-is 👍

**Pull request merged**
