### PR TITLE
Add details about the initial password

### PR DESCRIPTION
**Pull request by NataliaIvakina**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1792.surge.sh

Updated pages:
- [Linux executable (.tar)](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/linux/tarball)
- [macOS installation](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/osx)
- [Windows installation](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/windows)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1792.surge.sh

Updated pages:
- [Neo4j system service](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/linux/systemd)
- [Linux executable (.tar)](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/linux/tarball)
- [macOS installation](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/osx)
- [Windows installation](https://neo4j-docs-operations-1792.surge.sh/operations-manual/5/installation/windows)

**Review by renetapopova — COMMENTED** [review]
Thanks, @NataliaIvakina. It looks good, but I would suggest that @jennyowen review it because, as per the other card, Windows doesn't use the native neo4j user but a LocalSystem account.

**Review by jennyowen — APPROVED** [review]
I checked with @l-heemann about the windows thing you mentioned @renetapopova .
The `LocalSystem` user is most likely the Operating System user that runs the neo4j service and not related to user accounts within neo4j.

The default user account *inside neo4j* is always `neo4j`.

This PR adds a really nice clarification about the initial password. I like it!

**Pull request merged**
