### PR TITLE
Fixing page-aliases with more options to previous existing links

### PR DESCRIPTION
**Pull request by lidiazuin**
Related to this PR https://github.com/neo4j/docs-operations/pull/629

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1384.surge.sh

Updated pages:
- [Managing composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/manage-composite-databases)
- [Set up and query composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/querying-composite-databases)
- [Sharding data with the <code>copy</code> command](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/sharding-with-copy)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1384.surge.sh

Updated pages:
- [Built-in roles and privileges](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/built-in-roles)
- [Authentication and authorization](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization)
- [Recover admin user and password](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/password-and-user-recovery)
- [Command expansion](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/configuration/command-expansion)
- [Configuring remote database aliases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/aliases/remote-database-alias-configuration)
- [Concepts](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/concepts)
- [Managing composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/manage-composite-databases)
- [Set up and query composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/querying-composite-databases)
- [Sharding data with the <code>copy</code> command](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/sharding-with-copy)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1384.surge.sh

Updated pages:
- [Built-in roles and privileges](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/built-in-roles)
- [Authentication and authorization](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization)
- [Recover admin user and password](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/password-and-user-recovery)
- [Command expansion](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/configuration/command-expansion)
- [Configuring remote database aliases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/aliases/remote-database-alias-configuration)
- [Concepts](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/concepts)
- [Managing composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/manage-composite-databases)
- [Set up and query composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/querying-composite-databases)
- [Sharding data with the <code>copy</code> command](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/sharding-with-copy)

**Comment by renetapopova** [comment]
I think there are more `page-aliases` to be added, but let's see how these work.

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1384.surge.sh

Updated pages:
- [Built-in roles and privileges](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/built-in-roles)
- [Authentication and authorization](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization)
- [Recover admin user and password](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/authentication-authorization/password-and-user-recovery)
- [Command expansion](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/configuration/command-expansion)
- [Configuring remote database aliases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/aliases/remote-database-alias-configuration)
- [Concepts](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/concepts)
- [Managing composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/manage-composite-databases)
- [Set up and query composite databases](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/querying-composite-databases)
- [Sharding data with the <code>copy</code> command](https://neo4j-docs-operations-1384.surge.sh/operations-manual/5/database-administration/composite-databases/sharding-with-copy)

**Review by renetapopova — COMMENTED** [review]
All tested, should be fine.

**Pull request merged**
