### PR TITLE
Improve the checkpointing configurations descriptions and remove +++

### PR DESCRIPTION
**Pull request by renetapopova**
@stefano-ottolenghi, could you take a look and see if these changes would work for the testing?

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
Looks like you've updated the documentation!

Check out your changes at https://neo4j-docs-operations-838.surge.sh

**Comment by stefano-ottolenghi** [comment]
I have only looked at the first handful of settings, but I have noticed there have been significant changes to the descriptions and to valid values, in a way that makes their content different from the product, and it's not a matter of simple whitespace or formatting. Unless you also plan to submit those changes into Neo4j's source code, so that docs-in-the-product and these docs become equal again, we won't be able to test those fields. We can still check that all settings are present in the docs, but we cannot validate details.

**Comment by renetapopova** [comment]
> I have only looked at the first handful of settings, but I have noticed there have been significant changes to the descriptions and to valid values, in a way that makes their content different from the product, and it's not a matter of simple whitespace or formatting. Unless you also plan to submit those changes into Neo4j's source code, so that docs-in-the-product and these docs become equal again, we won't be able to test those fields. We can still check that all settings are present in the docs, but we cannot validate details. You may already be aware of this and happy with that, but I just wanted to ensure we are on the same page :)

Of course. I know that we should also change the descriptions in the code base. Otherwise, we can't test them. Maybe we should have a quick chat about this PR.

**Comment by renetapopova** [comment]
Replaced by #1062

**Pull request closed without merging**
