### PR TITLE
Prepare the connection setting descriptions for testing

### PR DESCRIPTION
**Pull request by renetapopova**
Depends on https://github.com/neo-technology/neo4j/pull/25751

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by NataliaIvakina** [comment]
don't look at files with antora errors, I'll fix them. Yesterday I fixed them on the 5.x branch

**Comment by renetapopova** [comment]
I fixed the log in another PR.

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)
- [Managing database aliases for standard databases](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/database-administration/aliases/manage-aliases-standard-databases)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1655.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/configuration/configuration-settings)
- [Managing database aliases for standard databases](https://neo4j-docs-operations-1655.surge.sh/operations-manual/5/database-administration/aliases/manage-aliases-standard-databases)

**Comment by renetapopova** [comment]
The failing test is not related to the updates in this PR.

**Comment by renetapopova** [comment]
Approved in the codebase.

**Pull request merged**
