### PR TITLE
Update config settings

### PR DESCRIPTION
**Pull request by NataliaIvakina**
related to:

- https://github.com/neo-technology/neo4j/pull/27220
- https://github.com/neo-technology/neo4j/pull/27762
- https://github.com/neo-technology/neo4j/pull/27695

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1923.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1923.surge.sh/operations-manual/5/configuration/configuration-settings)

**Review by renetapopova — COMMENTED** [review]
These two `dbms.cluster.minimum_initial_system_primaries_count` and `server.directories.cluster_state` also look like deprecated from 5.26. 
`dbms.cluster.network.supported_compression_algos` has a changed value from `emptyList` to `List.of`, but I don't know how this will be rendered in SHOW CONFIG.

**Comment by NataliaIvakina** [comment]
> These two `dbms.cluster.minimum_initial_system_primaries_count` and `server.directories.cluster_state` also look like deprecated from 5.26. `dbms.cluster.network.supported_compression_algos` has a changed value from `emptyList` to `List.of`, but I don't know how this will be rendered in SHOW CONFIG.

I'll take a look. I'll also ask someone from the clustering to review this PR when time comes to push all 5.26 changes

**Comment by NataliaIvakina** [comment]
I might be wrong but `dbms.cluster.minimum_initial_system_primaries_count` and `server.directories.cluster_state` are not deprecated in 5.26. Only the use of the port 5000 is deprecated (see the file).

**Comment by NataliaIvakina** [comment]
> `dbms.cluster.network.supported_compression_algos` has a changed value from `emptyList` to `List.of`, but I don't know how this will be rendered in SHOW CONFIG.

We don't have any default value for this config.
But I'll double check this moment when asking for a technical review

**Comment by renetapopova** [comment]
> I might be wrong but `dbms.cluster.minimum_initial_system_primaries_count` and `server.directories.cluster_state` are not deprecated in 5.26. Only the use of the port 5000 is deprecated (see the file).

Ah, I see now. Sorry for the confusion.

**Review by tonbut — APPROVED** [review]
LGTM

**Pull request merged**
