### PR TITLE
Clarify the `neo4j-admin.conf` file permissions for using `--expand-c…

### PR DESCRIPTION
**Pull request by NataliaIvakina**
…ommands`

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1591.surge.sh

Updated pages:
- [Command expansion](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/command-expansion)
- [Default file locations](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/file-locations)
- [Neo4j Admin and Neo4j CLI](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/tools/neo4j-admin)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1591.surge.sh

Updated pages:
- [Command expansion](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/command-expansion)
- [Default file locations](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/file-locations)
- [Neo4j Admin and Neo4j CLI](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/tools/neo4j-admin)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1591.surge.sh

Updated pages:
- [Command expansion](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/command-expansion)
- [Default file locations](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/file-locations)
- [Neo4j Admin and Neo4j CLI](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/tools/neo4j-admin)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1591.surge.sh

Updated pages:
- [Command expansion](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/command-expansion)
- [Default file locations](https://neo4j-docs-operations-1591.surge.sh/operations-manual/5/configuration/file-locations)

**Comment by NataliaIvakina** [comment]
I'd like to double-check one moment. In the file 'Default file locations', line 9, we talk about _minimal file permissions_. Are those minimal file permissions applicable to Unix, macOS, and Windows?

**Comment by zimmre** [comment]
@NataliaIvakina yes, there used generic words for permissions, like "Read only" or "Read and write", which is not linux specific bitmasks or windows acl, so applicable to all

**Review by zimmre — APPROVED** [review]
i think this is fine 👍

**Comment by NataliaIvakina** [comment]
> i think this is fine 👍

super! Thanks a lot

**Pull request merged**
