### PR TITLE
Fix group to role mapping section

### PR DESCRIPTION
**Pull request by l-heemann**
Related to: https://github.com/neo-technology/neo4j/pull/26072

### CODE REVIEW

**Comment by l-heemann** [comment]
https://trello.com/c/I2rLBLLQ/3908-sso-group-to-role-mapping-documentation-error

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1699.surge.sh

Updated pages:
- [Single sign-on integration](https://neo4j-docs-operations-1699.surge.sh/operations-manual/5/authentication-authorization/sso-integration)

**Review by renetapopova — APPROVED** [review]
Looks good from my side. Thanks, @l-heemann!

**Review by phil198 — APPROVED** [review]

**Comment by renetapopova** [comment]
@l-heemann, which version does this PR apply to?

**Comment by l-heemann** [comment]
> which version does this PR apply to?
What the documentation used to say has always been wrong. So... all of them?

**Pull request merged**
