### PR TITLE
added rhel 9.2 support to list and improved instructions around non-interactive rpm installation 

### PR DESCRIPTION
**Pull request by renetapopova**
Cherry-picked from #1074 and updated.

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1080.surge.sh

**Review by jennyowen — CHANGES_REQUESTED** [review]
Looks good. The bits about there being a 4.4 evaluation license are incorrect though.

**Comment by gijoe88** [comment]
Hi,
Here just to tell that in [the requirements page](https://neo4j.com/docs/operations-manual/4.4/installation/requirements/), the supported version of java on RedHat for Neo4J 4.4 has changed from 11 to 17 with this pull request. Was this intended?

**Comment by renetapopova** [comment]
> Hi, Here just to tell that in [the requirements page](https://neo4j.com/docs/operations-manual/4.4/installation/requirements/), the supported version of java on RedHat for Neo4J 4.4 has changed from 11 to 17 with this pull request. Was this intended?

No, good catch, @gijoe88!

**Pull request merged**
