### PR TITLE
Add bolt configs

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1474.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1474.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1474.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1474.surge.sh/operations-manual/5/configuration/configuration-settings)

**Comment by renetapopova** [comment]
This one can't be fixed. We should either exclude it from the test or decide that the test will always fail.
```
E   AssertionError: Mismatch in default value for setting db.tx_log.rotation.retention_policy.
    E   == Docs ==
    E   2 days 2G
    E   == Neo4j ==
    E   2 days
```

**Comment by stefano-ottolenghi** [comment]
I've fixed the failing test (and re-run them) so this PR is now good to be merged :)

**Pull request merged**
