### PR TITLE
Using quoting instead of escaping with backticks

### PR DESCRIPTION
**Pull request by renetapopova**
This is the only mention of escaping with backticks that I found in the Operations manual.

Cypher Manual PR: https://github.com/neo4j/docs-cypher/pull/1111

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1959.surge.sh

Updated pages:
- [Copy a database store](https://neo4j-docs-operations-1959.surge.sh/operations-manual/5/backup-restore/copy-database)
- [Managing database aliases in composite databases](https://neo4j-docs-operations-1959.surge.sh/operations-manual/5/database-administration/aliases/manage-aliases-composite-databases)

**Review by l-heemann — APPROVED** [review]
LGTM thanks!

**Comment by renetapopova** [comment]
Thanks, @l-heemann. I found more occurrences. I'll let you know when I commit them.

**Review by l-heemann — APPROVED** [review]
New commit LGTM

**Pull request merged**
