### PR TITLE
delete push to cloud page

### PR DESCRIPTION
**Pull request by fiquick**
See also https://github.com/neo4j/docs-operations/pull/1862

### CODE REVIEW

**Comment by NataliaIvakina** [comment]
What happened to the command `push-to-cloud` in 4.3? Is it deprecated, not supported? See https://neo4j.com/docs/operations-manual/4.3/tools/

**Comment by renetapopova** [comment]
4.3 is no longer a supported version, but we can't just delete a page because whatever is in the manual was supported when this version was supported. I think a better option would be to hide all unsupported versions from the version picker. I have created a card for that https://trello.com/c/G23oIBIg/56-hide-all-versions-that-we-dont-support-from-the-version-picker-in-the-operations-manual

**Comment by NataliaIvakina** [comment]
> 4.3 is no longer a supported version, but we can't just delete a page because whatever is in the manual was supported when this version was supported. I think a better option would be to hide all unsupported versions from the version picker. I have created a card for that https://trello.com/c/G23oIBIg/56-hide-all-versions-that-we-dont-support-from-the-version-picker-in-the-operations-manual

Yes, you're right. We discussed it with Ffion.

**Comment by fiquick** [comment]
Thank you for the support @NataliaIvakina and @renetapopova - I'm closing this PR

**Pull request closed without merging**
