### PR TITLE
added rhel 9.2 support to list and improved instructions around non-interactive rpm installation

### PR DESCRIPTION
**Pull request by jennyowen**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-operations-1074.surge.sh

**Review by renetapopova — APPROVED** [review]

**Comment by renetapopova** [comment]
@jennyowen, which version is this applicable to?

**Comment by jennyowen** [comment]
oh sorry! This is applicable to 4.4 and 5.x.

**Comment by renetapopova** [comment]
I'll cherry-pick it. Thanks, @jennyowen!

**Pull request merged**
