### PR TITLE
Remove legacy-backup and legacy-restore

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1461.surge.sh

Updated pages:
- [Back up an online database](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5/backup-restore/online-backup)
- [Restore a database backup](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5/backup-restore/restore-backup)
- [The Neo4j Operations Manual v5](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5)

**Comment by au-arena** [comment]
not needed, command removed

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1461.surge.sh

Updated pages:
- [Back up an online database](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5/backup-restore/online-backup)
- [Restore a database backup](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5/backup-restore/restore-backup)
- [The Neo4j Operations Manual v5](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1461.surge.sh

Updated pages:
- [Back up an online database](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5/backup-restore/online-backup)
- [The Neo4j Operations Manual v5](https://neo4j-docs-operations-1461.surge.sh/operations-manual/5)

**Review by au-arena — APPROVED** [review]

**Pull request merged**
