### PR TITLE
Add a note in restore a database backup to consider CDC implications

### PR DESCRIPTION
**Pull request by HannesSandberg**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1443.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1443.surge.sh/operations-manual/5/backup-restore/restore-backup)

**Comment by l-heemann** [comment]
LGTM, blocked on the section in CDC docs not being published. I've asked docs to publish those now.

**Review by l-heemann — APPROVED** [review]

**Review by renetapopova — CHANGES_REQUESTED** [review]
Looks good, just one suggestion you might want to consider. Thanks, @HannesSandberg

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1443.surge.sh

Updated pages:
- [Restore a database backup](https://neo4j-docs-operations-1443.surge.sh/operations-manual/5/backup-restore/restore-backup)

**Comment by l-heemann** [comment]
CDC docs have been released and the link works as expected 🚀

**Review by renetapopova — APPROVED** [review]
Looks good. Thanks, @HannesSandberg

**Pull request merged**
