### PR TITLE
Add missing metric <prefix>.transaction.validation_failure

### PR DESCRIPTION
**Pull request by renetapopova**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1544.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1544.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Comment by NataliaIvakina** [comment]
This metric is related to MVCC, which has not been released yet. On the other side, it's exposed to users, so we can publish it.

**Review by NataliaIvakina — APPROVED** [review]

**Comment by NataliaIvakina** [comment]
> I'm still trying to understand why the test fails with the missing CatchUp Metrics class, even though we have this class.

because of spelling: in the docs - CatchUp metrics  VS in the code CatchUp Metrics

**Comment by renetapopova** [comment]
> > I'm still trying to understand why the test fails with the missing CatchUp Metrics class, even though we have this class.
> 
> because of spelling: in the docs - CatchUp **m**etrics VS in the code - CatchUp **M**etrics

Capitalization! I saw this but thought, "No, that can't be the case".

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1544.surge.sh

Updated pages:
- [Metrics reference](https://neo4j-docs-operations-1544.surge.sh/operations-manual/5/monitoring/metrics/reference)

**Pull request merged**
