### PR TITLE
Add seed from URI differential backup support 

### PR DESCRIPTION
**Pull request by jackwaudby**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1989.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1989.surge.sh/operations-manual/5/clustering/databases)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1989.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1989.surge.sh/operations-manual/5/clustering/databases)

**Comment by NataliaIvakina** [comment]
Everything looks good. But I suggest not using labels in this case. It looks a little bit awkward on the page. Besides, there are too many labels on the page already.

**Comment by jackwaudby** [comment]
Sure thing, edits look good to me. Thank you! 🙇🏼

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1989.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1989.surge.sh/operations-manual/5/clustering/databases)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1989.surge.sh

Updated pages:
- [Managing databases in a cluster](https://neo4j-docs-operations-1989.surge.sh/operations-manual/5/clustering/databases)

**Review by NataliaIvakina — APPROVED** [review]

**Pull request merged**
