### PR TITLE
Deprecate database allocator

### PR DESCRIPTION
**Pull request by gfx54b**
Both initial settings and procedure to set.

Counterpart of https://github.com/neo-technology/neo4j/pull/26599

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1755.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1755.surge.sh/operations-manual/5/configuration/configuration-settings)
- [Procedures](https://neo4j-docs-operations-1755.surge.sh/operations-manual/5/reference/procedures)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1755.surge.sh

Updated pages:
- [Configuration settings](https://neo4j-docs-operations-1755.surge.sh/operations-manual/5/configuration/configuration-settings)
- [Procedures](https://neo4j-docs-operations-1755.surge.sh/operations-manual/5/reference/procedures)

**Review by renetapopova — APPROVED** [review]
looks good

**Comment by renetapopova** [comment]
The failing tests are not related to this PR.

**Pull request merged**
