### PR TITLE
Added a new page for the backup inspect command.

### PR DESCRIPTION
**Pull request by au-arena**

### CODE REVIEW

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1859.surge.sh

New pages:
- [Inspect the metadata of a database backup file.](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore/inspect)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1859.surge.sh

New pages:
- [Inspect the metadata of a database backup file.](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore/inspect)

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1859.surge.sh

New pages:
- [Inspect the metadata of a backup file](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore/inspect)

Updated pages:
- [Backup and restore](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore)

**Review by renetapopova — COMMENTED** [review]
Thanks, @au-arena! I have pushed some editorial updates. Could you please take a look to make sure I have kept the meaning of everything necessary? Thanks!

**Comment by neo-technology-commit-status-publisher** [comment]
This PR includes documentation updates
View the updated docs at https://neo4j-docs-operations-1859.surge.sh

New pages:
- [Inspect the metadata of a backup file](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore/inspect)

Updated pages:
- [Backup and restore](https://neo4j-docs-operations-1859.surge.sh/operations-manual/5/backup-restore)

**Review by renetapopova — APPROVED** [review]

**Pull request merged**
